version: '3.4'
services:
  go:
    image: acim/go-reflex
    container_name: CA_go
    depends_on:
      - db
    environment:
      - RACE_DETECTOR=1
      - RUN_ARGS=server
    volumes:
    - .:/app
    ports:
      - 8080:8080
    working_dir: /app
    command: reflex -r './*.go' -s -- sh -c 'go run .'

  db:
    image: mariadb:latest
    container_name: CA_db
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: 'ca@1234'
      MYSQL_DATABASE: 'ca_db'
    ports:
      - 3306:3306
    expose:
      - 3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: CA_phpmyadmin
    depends_on:
      - db
    ports:
      - 8000:80
    environment:
      PMA_HOST: db